!     ************************************
!     * Client Proxy Procedure Code
!     *    generated by rpcmake
!     *    on Friday, April 13, 2012 at 15:38:26
!     *    
!     * interface: basic_server 
!     *    
!     ************************************

SUB CLIENT(  & 
                I,  &
                F,  &
                D,  &
                STRNG,  &
                DCE-RESULT) 
 EXTERNAL FUNCTION dce_find_server(   &
                   STRING BY DESC,  &
                   INTEGER BY REF,  &
                   INTEGER BY REF)  
 DECLARE INTEGER SOCKET 
 DECLARE STRING SERVER_NAME 
 SERVER_NAME="BASFUNC" 
      CALL dce_checkver ( &
                , &
                )

           CALL dce_findserver_ref ( SERVER_NAME , SOCKET) 
           IF SOCKET >= 0 
                 CBUFFER$ = 'i' + STRING$(1%, 0%)
                 CALL dce_push_int_vms_ref(SOCKET, CBUFFER$, i)
                 CBUFFER$ = 'f' + STRING$(1%, 0%)
                 CALL dce_push_float_vms_ref(SOCKET, CBUFFER$, f)
                 CBUFFER$ = 'd' + STRING$(1%, 0%)
                 CALL dce_push_float_vms_ref(SOCKET, CBUFFER$, d)
                 CBUFFER$ = 'strng' + STRING$(1%, 0%)
                 D_MAGS = 50
                 CALL dce_push_char_str_vms_ref    &
             ( SOCKET, CBUFFER$,     &
              strng$, D_MAGS)
                CALL dce_submit_ref (SERVER-NAME,   &
                     CBUFFER$, SOCKET, DCE_TABLE )

                 LET strng= SPACE$(100)
                 LET CBUFFER$= "dce_result" + STRING$(1%, 0%) 
                 CALL dce_pop_int_vms_ref(DCE_TABLE, CBUFFER$, dce_result)
                CALL dce_table_destroy_ref ( DCE_TABLE)
                CALL dce_release_ref
           END IF 
      END SUB 


